name: "PR Reviewer - AI Code Review & Fixes"
description: "AI-powered code reviews that detect issues, provide summaries, and suggest auto-fixes on PRs."
author: "shawnd"
branding:
  icon: "check-square"
  color: "black"
  tags: "ai,code-review,ai-assisted,automation,pull-requests,linting,ci,autofix,devtools"

runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  style_guide_rules:
    required: false
    description: 'Custom style guide rules that will be enforced during review by generating critical comments'
    default: ''
  github_api_url:
    required: false
    description: 'GitHub API URL for GitHub Enterprise Server (e.g., https://github.example.com/api/v3)'
    default: 'https://api.github.com'
  github_server_url:
    required: false
    description: 'GitHub Server URL for GitHub Enterprise Server (e.g., https://github.example.com)'
    default: 'https://github.com'
